theme: jekyll-theme-slate
title: Github Pages Resources
description: Code, HowTo, Help etc...
excerpt_separator: "<!--more-->"
baseurl: "/resources/"
permalink: /:title/
# The release of Jekyll Now that you're using
version: v1.2.0
plugins:
  - jekyll-relative-links
